server {
    listen 8088;
    server_name localhost;

    client_max_body_size 100m;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
